### ISSUE TITLE
Parameter sliders behavior

### ISSUE THREAD

**Issue by ChucklesOnGitHub** [open-ephys/bonsai-miniscope#25]
Some observations that may or may not need revising.

MiniCAM:
- FramesPerSecond is a slider but consecutive numbers are 7 keypresses apart instead of 1.
- LedBrightness is fractional (weird) and the maximum is 26 (intended?)
![image](https://github.com/user-attachments/assets/a96d5a5e-0e94-4bcc-8106-3fa78abcd41f)

Miniscope v4:
- Focus: slider is also fractional (weird). Is the range +/-100 to avoid confusion with the actual +/-200 mum scale because it is not calibrated?
![image](https://github.com/user-attachments/assets/ef474ad2-7ff2-4c95-b297-6fc528fb5614)

- FramesPerSecond list has one item out of order:
![image](https://github.com/user-attachments/assets/89ed3133-77e4-47ab-a259-685fef22f6dc)

- LedBrightness is fractional (weird), but maximum ok at 100. This makes it hard for users to note down what setting they used.
- In the Onix library there is an interleave LED that is not here, idk if relevant.

In all the sliders the right and left arrow keys work as expected but up arrow decreases the values and down arrow increases, maybe more of a Bonsai issue?

**Comment by jonnew** [comment]
MiniCAM:
- FramesPerSecond : changed to numeric up down
- Led brightness: reduce decimal places to 1

Miniscope v4:
- Focus slider:  
  -  Reduce decimal places to 1. 
  - The focus range is not well defined. The description of this control is correct: "Electro-wetting lens focal plane adjustment (percent of range around nominal)." (wontfix)
- FramesPerSecond: reordered
- LedBrightness :  reduce decimal places to 1
- Interleaved LED: for some reason, this does not work via the DAQ. I don't know why but it would take time to investigate that I don't have.
- Sensor Gain: reordered Low, Med, High
